### ISSUE TITLE
Not sure if you even look at this repository anymore but running into an issue with MAL

### ISSUE THREAD

**Issue by JourneyOver** [frosty5689/docker-trackma#2]
Got everything all set up and going but whenever I am running with MAL it just keeps outputting
```
APIFatal: This account seems to be using the old MyAnimeList API.Please re-create and authorize the account.
```

I have deleted the config files multiple times over but no matter what I seem to do it just does not seem to work, running it outside of docker works just fine, so I also tried copy+pasting the config files over and it didn't seem to matter any as it still just throws the same error message.

Though I did notice one thing as well in that this seems to be running 0.8.4 release, while the latest release is 0.8.5 which I guess could be the actual issue on why this is maybe happening??

**Comment by frosty5689** [comment]
I can try upgrading to latest version. No guarantees MAL APIs will work. They deprecated all their APIs a few years ago. Not sure if they added any of it back.

I have exported MAL and imported into AniList and using anilist plex sync for the last few years.

**Comment by JourneyOver** [comment]
@frosty5689 so I did look into people who forked this repository and found one https://github.com/TheVexedGerman/docker-trackma that had set up to run a temporary webserver to accept OAuth key and it seemed to work. 

Though it had the same issue of it being a version behind as well on top of the fact that if you restart the container for whatever reason you have to go back and redo the auth again because it otherwise just hangs on the temporary webserver bit..


I assume you are talking about https://github.com/RickDB/PlexAniSync when it comes to the anilist plex sync thing? I might look into that even though I do prefer MAL and/or kitsu :x

**Comment by frosty5689** [comment]
Yeah.. The new MAL API sucks.

Yep that's the one. It works pretty well if it can match. Though there are some shows that don't match if you use HAMA which uses anidb.

**Comment by JourneyOver** [comment]
Hmm okay I might switch over to using that instead and just use a chrome extension to automate syncing from anilist to MAL and Kitsu then.. and ha I used to have so many issues with HAMA and dealing with syncing for other places in the past that I kind of gave up using it as an agent for plex. 

tbh I don't even know what site most people use nowdays anyways for tracking anime since I've been out of the loop on anime for along time but kind of want to start getting back into it again xD

**Comment by frosty5689** [comment]
AniList has been gaining users as MAL went downhill. It is more modern and gets updated just as quickly

**Comment by JourneyOver** [comment]
I'm going to go ahead and close this issue, I've pretty much moved over to using PlexAniSync and Anilist for a backup of all my anime shows/movies watched/finding new recommendations.
